name:                ad-hoc-poly
version:             0.1.0.0
github:              "coord-e/ad-hoc-poly"
license:             BSD3
author:              "coord.e"
maintainer:          "me@coord-e.com"
copyright:           "2019 coord.e"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/coord-e/ad-hoc-poly#readme>

dependencies:
- base >= 4.7 && < 5
- recursion-schemes
- lens
- containers
- mtl
- extensible-effects
- extra
- safe
- megaparsec
- parser-combinators
- yaml
- aeson
- text
- array

ghc-options:
- -Wall
- -Wno-simplifiable-class-constraints

library:
  source-dirs: src

executables:
  mlx1:
    main:                Mlx1.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Mlx1
    dependencies:
    - ad-hoc-poly

  mlx2:
    main:                Mlx2.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Mlx2
    dependencies:
    - ad-hoc-poly

tests:
  ad-hoc-poly-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ad-hoc-poly
    - hspec
    - shelly
    - temporary
